# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Quantum Cryptography Cryptography
author: Brianna Laird
logo: logo.png
copyright: "2024"
# Patterns to skip when building the book. Can be glob-style (e.g. "*skip.ipynb")
exclude_patterns: [my-running-guide.md, report-file.ipynb]

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: false

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/breezy-codes/quantum-cryptography-guide  # Online location of your book
  
# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  favicon: favicon.png
  use_issues_button: true
  use_repository_button: true
  use_multitoc_numbering: false

sphinx:
  extra_extensions:
    - sphinx_proof
