name: Deploy Jupyter Book to GitHub Pages

on:
  push:
    branches:
      - pages  # Replace with the branch you use for your source files

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install dependencies
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # Build the Jupyter Book
      - name: Build the Jupyter Book
        run: jupyter-book build .

      # Ensure the CNAME file is in the built HTML directory
      - name: Add CNAME file
        run: echo "cheat-sheets.breezy-codes.com" > _build/html/CNAME

      # Upload the book's HTML as an artifact (Updated to v3)
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "_build/html"

      # Deploy the book's HTML to GitHub Pages (Updated to v4)
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
